"""Apply per-country party-name → partyfacts_id mapping.

Reads the long-format poll-party CSVs and the country mapping YAML, then
writes harmonized CSVs to data/interim/harmonized/{COUNTRY}.csv.

YAML mapping accepts two shapes:

  1. Dict (hand-curated, e.g. IT.yaml):
         mappings:
           FdI: { partyfacts_id: 2280, notes: "..." }
  2. List (auto-generated by scripts/party_crosswalk_build.py):
         mappings:
           - party_short: FdI
             partyfacts_id: 2280
             source: gemini_high
             confidence: high
             is_coalition: false
             notes: "..."

Both shapes are normalized to a dict keyed by ``party_short`` with the
unioned set of fields (``partyfacts_id``, ``source``, ``confidence``,
``is_coalition``, ``notes``, ``drop``).

Usage:
    python -m europolls.harmonize IT DE FR
"""
from __future__ import annotations

import argparse
import csv
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
IN_DIR = ROOT / "data" / "interim"
OUT_DIR = ROOT / "data" / "interim" / "harmonized"
MAP_DIR = ROOT / "config" / "party_mappings"

OUT_COLS = [
    "partyfacts_id",
    "partyfacts_id_source",
    "partyfacts_id_confidence",
    "partyfacts_id_notes",
    "is_dropped_meta",
    "dropped_meta_reason",
]

# drop_reason values removed entirely from per-country harmonized output
# (kept in sync with scripts.build_all.HARD_DROP_REASONS).
# Coalition collapsing (drop coalition rows when single-party rows exist
# for the same poll) is applied only at the concat step.
HARD_DROP_REASONS = {
    "approval", "lead", "response_rate", "total",
    "presidential_candidate", "parse_artifact",
}


def _normalize_entry(entry: dict) -> dict:
    """Coerce one mapping entry to the canonical field set.

    If ``source`` is omitted, infer it:
      * present-but-null partyfacts_id → ``verified_not_in_pf``
      * concrete partyfacts_id         → ``hand_curated``
    so downstream consumers can distinguish "checked, no PF match" from
    "no YAML entry at all".
    """
    pfid = entry.get("partyfacts_id")
    source = entry.get("source")
    if source is None and not entry.get("drop"):
        source = "verified_not_in_pf" if pfid is None else "hand_curated"
    return {
        "partyfacts_id": pfid,
        "source": source,
        "confidence": entry.get("confidence"),
        # IT.yaml uses `coalition`; auto-gen uses `is_coalition`.
        "is_coalition": bool(entry.get("is_coalition") or entry.get("coalition")),
        "notes": entry.get("notes") or "",
        "drop": bool(entry.get("drop")),
        "drop_reason": entry.get("drop_reason") or "",
    }


def _load_yaml_mappings(path: Path) -> dict[str, dict]:
    with path.open() as f:
        raw = (yaml.safe_load(f) or {}).get("mappings")
    if raw is None:
        return {}
    if isinstance(raw, dict):
        return {short: _normalize_entry(v or {}) for short, v in raw.items()}
    out: dict[str, dict] = {}
    for entry in raw:
        short = entry.get("party_short")
        if short is None:
            continue
        out[short] = _normalize_entry(entry)
    return out


def load_meta_mapping() -> dict[str, dict]:
    """Global cross-country meta-label drops (party_mappings/_meta.yaml)."""
    path = MAP_DIR / "_meta.yaml"
    if not path.exists():
        return {}
    return _load_yaml_mappings(path)


def load_mapping(country: str) -> dict[str, dict]:
    """Per-country mapping merged with the global meta-drop list.

    Precedence:
      * per-country wins for parties with a real partyfacts_id;
      * meta `drop: true` wins when the per-country entry has no
        partyfacts_id (e.g. a stale ``gemini_no_match`` that we've
        since recognized as a meta-label like ``Resp.|Response rate``).
    """
    path = MAP_DIR / f"{country}.yaml"
    if not path.exists():
        raise FileNotFoundError(f"no mapping file at {path}")
    meta = load_meta_mapping()
    merged = dict(meta)
    for short, entry in _load_yaml_mappings(path).items():
        meta_entry = meta.get(short)
        if (meta_entry is not None and meta_entry["drop"]
                and entry.get("partyfacts_id") is None):
            continue  # keep the meta drop, ignore the per-country no-match
        merged[short] = entry
    return merged


def harmonize(country: str) -> None:
    mapping = load_mapping(country)
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    in_files = sorted(IN_DIR.glob(f"{country}_*.csv"))
    if not in_files:
        raise FileNotFoundError(f"no input files for {country} in {IN_DIR}")

    n_in = 0
    n_drop = 0
    n_kept = 0
    n_unmapped = 0
    unmapped_shorts: dict[str, int] = {}

    out_path = OUT_DIR / f"{country}_long_harmonized.csv"
    writer = None
    with out_path.open("w", newline="") as f_out:
        for in_path in in_files:
            with in_path.open() as f_in:
                reader = csv.DictReader(f_in)
                if writer is None:
                    base = list(reader.fieldnames)
                    extra = [c for c in OUT_COLS if c not in base]
                    fieldnames = base + extra
                    writer = csv.DictWriter(f_out, fieldnames=fieldnames)
                    writer.writeheader()
                for row in reader:
                    n_in += 1
                    short = row["party_short"]
                    m = mapping.get(short)
                    if m is not None and m["drop_reason"] in HARD_DROP_REASONS:
                        n_drop += 1
                        continue
                    if m is None:
                        n_unmapped += 1
                        unmapped_shorts[short] = unmapped_shorts.get(short, 0) + 1
                        for c in OUT_COLS:
                            row[c] = ""
                        writer.writerow(row)
                        n_kept += 1
                        continue
                    if m["drop"]:
                        n_drop += 1
                        for c in OUT_COLS:
                            row[c] = ""
                        row["is_dropped_meta"] = "1"
                        row["dropped_meta_reason"] = m["drop_reason"]
                        writer.writerow(row)
                        continue
                    pfid = m["partyfacts_id"]
                    row["partyfacts_id"] = str(pfid) if pfid is not None else ""
                    row["partyfacts_id_source"] = m["source"] or ""
                    row["partyfacts_id_confidence"] = m["confidence"] or ""
                    row["partyfacts_id_notes"] = m["notes"]
                    row["is_dropped_meta"] = ""
                    row["dropped_meta_reason"] = ""
                    # OR YAML coalition flag onto the parse-time value.
                    if m["is_coalition"]:
                        row["is_coalition"] = "True"
                    writer.writerow(row)
                    n_kept += 1

    print(f"{country}: harmonized {n_in:,} input rows")
    print(f"  kept (written):    {n_kept:,}")
    print(f"  dropped meta:      {n_drop:,}")
    print(f"  unmapped shorts:   {n_unmapped:,}  (across {len(unmapped_shorts)} distinct shorts)")
    if unmapped_shorts:
        top_unmapped = sorted(unmapped_shorts.items(), key=lambda kv: -kv[1])[:15]
        print(f"  top unmapped:")
        for short, n in top_unmapped:
            print(f"    {short!r:<35} {n:>5}")
    print(f"  → {out_path.relative_to(ROOT)}")


def load_all_mappings() -> dict[str, dict[str, dict]]:
    """Return ``{country: {party_short: normalized_entry}}`` for every
    per-country YAML, with the global meta-drop list merged into each.

    Files starting with ``_`` (e.g. ``_meta.yaml``) are not countries
    and are skipped — their content is folded in via ``load_mapping``.
    """
    out: dict[str, dict[str, dict]] = {}
    for path in sorted(MAP_DIR.glob("*.yaml")):
        if path.stem.startswith("_"):
            continue
        out[path.stem] = load_mapping(path.stem)
    return out


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("countries", nargs="+")
    args = ap.parse_args()
    for c in args.countries:
        harmonize(c)


if __name__ == "__main__":
    main()
